# Generated by Django 2.1.4 on 2019-02-18 14:37

from django.db import migrations, models
import django.db.models.deletion
import provisioning.utils
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('identity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdentityCreation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(help_text='username choosen by user', max_length=128)),
                ('ldap_dn', models.CharField(max_length=254)),
                ('create_date', models.DateTimeField(auto_now=True)),
                ('identity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='identity.Identity')),
            ],
            options={
                'verbose_name': 'Identity Creation',
                'verbose_name_plural': 'Identity Creations',
            },
        ),
        migrations.CreateModel(
            name='IdentityLdapChangeConfirmation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(blank=True, default=uuid.uuid4, help_text='/create/$token', unique=True)),
                ('sent', models.BooleanField(default=False)),
                ('sent_to', models.CharField(blank=True, max_length=254, null=True)),
                ('sent_date', models.DateTimeField(blank=True, null=True)),
                ('valid_until', models.DateTimeField(blank=True, default=provisioning.utils.get_default_valid_until)),
                ('used', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='disable it if needed')),
                ('create_date', models.DateTimeField(auto_now=True)),
                ('ldap_dn', models.CharField(blank=True, default='', max_length=254)),
                ('current_data', models.TextField(blank=True, default='{}')),
                ('new_data', models.TextField(blank=True, default='{}')),
            ],
            options={
                'verbose_name': 'Identity Ldap Attributes Confirmation Change Token',
                'verbose_name_plural': 'Identity Ldap Attributes Confirmation Change Tokens',
            },
        ),
        migrations.CreateModel(
            name='IdentityLdapPasswordReset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(blank=True, default=uuid.uuid4, help_text='/create/$token', unique=True)),
                ('sent', models.BooleanField(default=False)),
                ('sent_to', models.CharField(blank=True, max_length=254, null=True)),
                ('sent_date', models.DateTimeField(blank=True, null=True)),
                ('valid_until', models.DateTimeField(blank=True, default=provisioning.utils.get_default_valid_until)),
                ('used', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='disable it if needed')),
                ('create_date', models.DateTimeField(auto_now=True)),
                ('ldap_dn', models.CharField(max_length=254)),
            ],
            options={
                'verbose_name': 'Identity Password Reset Token',
                'verbose_name_plural': 'Identity Password Reset Tokens',
            },
        ),
        migrations.CreateModel(
            name='IdentityProvisioning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(blank=True, default=uuid.uuid4, help_text='/create/$token', unique=True)),
                ('sent', models.BooleanField(default=False)),
                ('sent_to', models.CharField(blank=True, max_length=254, null=True)),
                ('sent_date', models.DateTimeField(blank=True, null=True)),
                ('valid_until', models.DateTimeField(blank=True, default=provisioning.utils.get_default_valid_until)),
                ('used', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='disable it if needed')),
                ('create_date', models.DateTimeField(auto_now=True)),
                ('ldap_dn', models.CharField(blank=True, max_length=254, null=True)),
                ('identity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='identity.Identity')),
            ],
            options={
                'verbose_name': 'Identity Account Creation token',
                'verbose_name_plural': 'Identity Account Creation tokens',
            },
        ),
    ]
