# Generated by Django 2.1.4 on 2019-02-22 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provisioning', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ldap_dn', models.CharField(max_length=254)),
                ('create_date', models.DateTimeField(auto_now=True)),
                ('sent', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Identity Ldap account expiration Notification',
                'verbose_name_plural': 'Identity Ldap account expiration Notifications',
            },
        ),
        migrations.AlterField(
            model_name='identityldapchangeconfirmation',
            name='ldap_dn',
            field=models.CharField(max_length=254),
        ),
    ]
