# Generated by Django 2.1.4 on 2019-02-22 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provisioning', '0002_auto_20190222_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='expiration_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
