# Generated by Django 2.1.4 on 2019-02-22 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provisioning', '0003_notifications_expiration_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='remaining_days',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
