# Generated by Django 2.2.10 on 2020-02-14 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provisioning', '0004_notifications_remaining_days'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangedUsername',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_username', models.CharField(blank=True, max_length=254, null=True)),
                ('old_username', models.CharField(max_length=254)),
                ('create_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Changed Usernames',
                'verbose_name': 'Changed Username',
            },
        ),
    ]
