# Generated by Django 2.1.4 on 2019-02-19 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='identity',
            old_name='data_attivazione',
            new_name='activation_date',
        ),
    ]
