# Generated by Django 3.0.5 on 2020-05-09 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0003_auto_20200211_1545'),
    ]

    operations = [
        migrations.RenameField(
            model_name='identity',
            old_name='email',
            new_name='mail',
        ),
        migrations.RemoveField(
            model_name='identity',
            name='fiscal_code',
        ),
        migrations.AddField(
            model_name='identity',
            name='tin',
            field=models.CharField(help_text="Tax Payer's Number or UniqueID", max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='addresstype',
            name='name',
            field=models.CharField(help_text='delivery type as mail, telephone...', max_length=12, unique=True),
        ),
    ]
