# Generated by Django 3.0.5 on 2020-05-09 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0004_auto_20200509_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='identity',
            name='gender',
            field=models.CharField(blank=True, choices=[('m', 'Male'), ('f', 'Female'), ('o', 'Other')], max_length=3, null=True),
        ),
    ]
