# Generated by Django 3.0.5 on 2020-05-09 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0005_identity_gender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='identity',
            old_name='nation',
            new_name='nation_of_bird',
        ),
    ]
