# Generated by Django 3.0.6 on 2020-05-14 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0008_auto_20200509_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identity',
            name='affiliation',
            field=models.CharField(choices=[('student,member', 'student [student, member]'), ('member', 'associato (ad es. CNR), consorziato (membro del consorzio a cui l"ente appartiene), dipendente altra università o ente di ricerca o azienda sanitaria/ospedaliera/policlinico, dottorando di altra università (consorziata), laureato frequentatore/collaboratore di ricerca (a titolo gratuito) [member]'), ('', 'cessato'), ('affiliate', 'convenzionato (cliente delle convenzioni), fornitore (dipendente o titolare delle ditte fornitrici), ispettore, ospite / visitatore [affiliate]'), ('staff,member', 'dipendente, professore, ricercatore, titolare di assegno di ricerca, tutor, assistente universitario, collaboratore coordinato continuativo, collaboratore linguistico, cultore della materia [staff, member]'), ('staff,member,student', 'dottorando, specializzando [staff, member, student]'), ('member', 'lettore di scambio, titolare di borsa di studio, volontario servizio civile nazionale [member]'), ('student', 'studente erasmus in ingresso [student]'), ('student,member', 'studente, studente fuori sede (tesista, tirocinante, ...), studente laurea specialistica, studente master, studente siss [member, student]')], default='student,member', help_text='Affiliation', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='identity',
            name='gender',
            field=models.CharField(blank=True, choices=[(0, 'Not know'), (1, 'Male'), (2, 'Female'), (9, 'Not specified')], max_length=3, null=True),
        ),
    ]
