# Generated by Django 2.2.10 on 2020-02-14 09:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_matricola'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='access_notification',
            field=models.BooleanField(default=True, help_text='enable email send', verbose_name='Invia email di notifica accesso'),
        ),
        migrations.CreateModel(
            name='LdapDump',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dump', models.TextField(verbose_name='Json attributes')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
