# Generated by Django 2.2.10 on 2020-02-14 09:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200214_1032'),
    ]

    operations = [
        migrations.AddField(
            model_name='ldapdump',
            name='modified',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
