# Generated by Django 2.2.10 on 2020-02-19 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_user_change_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='change_username',
            field=models.BooleanField(default=False, verbose_name='Allow user to change his username'),
        ),
    ]
