# Generated by Django 3.0.5 on 2020-04-26 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_change_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='location',
            new_name='place_of_birth',
        ),
        migrations.AlterField(
            model_name='user',
            name='codice_fiscale',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name="TIN - Tax payer's Identification number"),
        ),
    ]
