# Generated by Django 3.0.6 on 2020-05-16 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20200426_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ldapdump',
            name='dump',
            field=models.TextField(verbose_name='Attributi in formato JSON'),
        ),
        migrations.AlterField(
            model_name='user',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data di nascta'),
        ),
        migrations.AlterField(
            model_name='user',
            name='change_username',
            field=models.BooleanField(default=False, verbose_name='Consente agli utenti di modificare il proprio username'),
        ),
        migrations.AlterField(
            model_name='user',
            name='codice_fiscale',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Codice di identificazione Nazionale'),
        ),
        migrations.AlterField(
            model_name='user',
            name='place_of_birth',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Luogo di nascita'),
        ),
    ]
