# Generated by Django 3.0.6 on 2020-06-12 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountUpdateLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=150, null=True, verbose_name='Type')),
                ('uid', models.CharField(blank=True, max_length=135, null=True, verbose_name='Account id')),
                ('backup', models.TextField(verbose_name='Attributi in formato JSON')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='creato')),
            ],
            options={
                'verbose_name_plural': 'Account update logs',
            },
        ),
    ]
